package com.adashrod.scannerdaemon;

/**
 * API for plugins to interact with the main program.
 */
public class PluginApi {
    private final ScanRecord scanRecord;

    public PluginApi(final ScanRecord scanRecord) {
        this.scanRecord = scanRecord;
    }

    /**
     * The scan record is a text file used to keep track of which files have been scanned by the daemon and generated by
     * demuxing. Calling this with a filename will add it to the record, indicating that it should be ignored by future
     * scans.
     * @param filename name of the file to exclude in the future
     */
    public void addToScanRecord(final String filename) {
        scanRecord.addSuccess(filename);
    }
}
